server:
  port: 8001 #服务端口号
spring:
  application:
    name: demo-8001  #微服务名称，对外暴漏的微服务名称，十分重要
########################################### Spring cloud 自定义服务名称和 ip 地址###############################################
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）

  instance:
    instance-id: demo-8001 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址
